# Generated by Django 5.1.4 on 2025-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_realtor_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='referral_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
