# Generated by Django 5.1.4 on 2025-04-28 00:04

import django.db.models.deletion
import django.utils.timezone
import estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_realtor_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=estate.models.PropertySale.generate_reference_number, editable=False, max_length=12, unique=True)),
                ('estate_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('building', 'Building Property'), ('land', 'Land')], max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Number of plots or buildings')),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField()),
                ('client_phone', models.CharField(max_length=20)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_address', models.TextField()),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_plan', models.CharField(choices=[('outright', 'Outright Purchase'), ('3_months', '3 Months Plan'), ('6_months', '6 Months Plan')], default='outright', max_length=10)),
                ('realtor_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sponsor_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upline_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='estate.property')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='estate.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='Cash', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('property_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='estate.propertysale')),
            ],
        ),
    ]
