# Generated by Django 5.1.4 on 2025-04-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_property_propertysale_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='propertysale',
            old_name='linked_property',
            new_name='property',
        ),
    ]
