# Generated by Django 5.1.4 on 2025-04-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysale',
            old_name='estate_name',
            new_name='description',
        ),
    ]
