# Generated by Django 5.1.4 on 2025-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_propertysale_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_account_ame', models.CharField(blank=True, max_length=150, null=True)),
                ('company_account_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
