# Generated by Django 5.1.4 on 2025-05-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_general'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='company_account_ame',
            new_name='company_account_name',
        ),
    ]
