# Generated by Django 5.1.4 on 2025-05-08 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_rename_company_account_ame_general_company_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(choices=[('redan_city', 'REDAN CITY'), ('canaan_city', 'CANAAN CITY ESTATE'), ('vatican_garden', 'VATICAN GARDEN')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='estate_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in slider')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estate Image',
                'verbose_name_plural': 'Estate Images',
                'ordering': ['estate', 'order', '-created_at'],
            },
        ),
    ]
