# Generated by Django 5.1.4 on 2025-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_estateimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['status', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='realtor',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular Realtor'), ('executive', 'Executive Realtor')], default='regular', help_text='Realtor status - can be changed by admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='estateimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='realtor',
            index=models.Index(fields=['status'], name='estate_real_status_b71ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='realtor',
            index=models.Index(fields=['referral_code'], name='estate_real_referra_2d0ac2_idx'),
        ),
    ]
