# Generated by Django 5.1.4 on 2025-05-31 10:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0015_alter_realtor_account_number_alter_realtor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formupload',
            name='form_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='forms/'),
        ),
    ]
