# Generated by Django 5.1.4 on 2025-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_alter_formupload_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
