# Generated by Django 5.1.4 on 2025-06-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0018_alter_realtor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='client_picture',
            field=models.ImageField(blank=True, default='user/images/pph.jpeg', null=True, upload_to='client_pictures/'),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
