# Generated by Django 5.1.4 on 2025-06-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0020_alter_propertysale_client_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertysale',
            name='client_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_pictures/'),
        ),
    ]
