# Generated by Django 5.1.4 on 2025-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_realtor_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
