# Generated by Django 5.1.4 on 2025-07-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0022_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='plot_development_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='plot_development_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
