# Generated by Django 5.1.4 on 2025-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0023_propertysale_plot_development_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='is_developed',
            field=models.BooleanField(default=False, help_text='Mark as True when client has developed the property'),
        ),
    ]
