# Generated by Django 5.2.4 on 2025-11-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0026_payment_created_at_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin or secretary who registered this property sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_sales_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
