# Generated by Django 5.2.4 on 2025-11-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0026_payment_created_at_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who registered this property sale', max_length=255, null=True, verbose_name='Created By'),
        ),
    ]
